<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ChainsawBONELABCodeMod</AssemblyName>
    <RootNamespace>ChainsawBONELABCodeMod</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader" HintPath="References/MelonLoader.dll" Private="false" />
    <Reference Include="BoneLib" HintPath="References/BoneLib.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="References/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="References/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="References/UnityEngine.PhysicsModule.dll" Private="false" />
  </ItemGroup>
</Project>
